import { toDateKey, addDays, startOfWeek } from './date';

export const MISS_REASONS = [
  { id: 'time', label: 'Not enough time' },
  { id: 'priority', label: 'Priorities changed' },
  { id: 'forgot', label: 'Forgot' },
  { id: 'energy', label: 'Low energy' },
  { id: 'other', label: 'Other' },
];

const reasonLabel = (id) =>
  id === 'unspecified' ? 'No reason given' : (MISS_REASONS.find((r) => r.id === id)?.label ?? id);

const createdKey = (habit) => toDateKey(new Date(habit.createdAt));
const percent = (rate) => `${Math.round(rate * 100)}%`;
const weekday = (day) => day.date.toLocaleDateString('en-US', { weekday: 'long' });

// All numbers in a weekly summary are computed here, never generated by a model.
// Only fully finished days count, so an unfinished "today" never drags the rate down.
export function computeWeek({ habits, completions, misses = {} }, weekStart, today = new Date()) {
  const todayKey = toDateKey(today);

  const days = Array.from({ length: 7 }, (_, index) => {
    const date = addDays(weekStart, index);
    const key = toDateKey(date);
    const counted = key < todayKey;
    const eligibleHabits = counted ? habits.filter((h) => createdKey(h) <= key) : [];
    const done = eligibleHabits.filter((h) => (completions[h.id] || []).includes(key)).length;
    return {
      date,
      key,
      counted,
      eligibleHabits,
      eligible: eligibleHabits.length,
      done,
      rate: eligibleHabits.length ? done / eligibleHabits.length : null,
    };
  });

  const habitStats = habits.map((habit) => ({ habit, eligible: 0, done: 0, rate: null }));
  const reasonCounts = {};
  let flagged = false;

  days.forEach((day) => {
    day.eligibleHabits.forEach((habit) => {
      const stat = habitStats.find((s) => s.habit.id === habit.id);
      stat.eligible += 1;
      if ((completions[habit.id] || []).includes(day.key)) {
        stat.done += 1;
        return;
      }
      const miss = misses[habit.id]?.[day.key];
      const reason = miss?.reason || 'unspecified';
      reasonCounts[reason] = (reasonCounts[reason] || 0) + 1;
      if (miss?.flagged) flagged = true;
    });
  });

  habitStats.forEach((stat) => {
    stat.rate = stat.eligible ? stat.done / stat.eligible : null;
  });

  const eligible = days.reduce((sum, d) => sum + d.eligible, 0);
  const done = days.reduce((sum, d) => sum + d.done, 0);

  return {
    weekStart,
    days,
    habitStats: habitStats.filter((s) => s.eligible > 0),
    eligible,
    done,
    rate: eligible ? done / eligible : null,
    reasons: Object.entries(reasonCounts)
      .map(([id, count]) => ({ id, label: reasonLabel(id), count }))
      .sort((a, b) => b.count - a.count),
    flagged,
  };
}

export function previousWeek(data, summary, today) {
  return computeWeek(data, addDays(summary.weekStart, -7), today);
}

export function trendWeeks(data, weekStart, count = 4, today = new Date()) {
  return Array.from({ length: count }, (_, index) => {
    const start = addDays(weekStart, -7 * (count - 1 - index));
    return { weekStart: start, rate: computeWeek(data, start, today).rate };
  });
}

// Earliest/current week and which week to show first: the last finished week if it has data.
export function getWeekBounds(data, today = new Date()) {
  const current = startOfWeek(today);
  const created = data.habits.map((h) => startOfWeek(new Date(h.createdAt)).getTime());
  const earliest = created.length ? new Date(Math.min(...created)) : current;
  const last = addDays(current, -7);
  const hasLast = last >= earliest && computeWeek(data, last, today).rate !== null;
  return { earliest, current, initial: hasLast ? last : current };
}

function extremes(items, getRate) {
  const rated = items.filter((item) => getRate(item) !== null);
  if (rated.length < 2) return { best: null, worst: null };
  const best = rated.reduce((a, b) => (getRate(b) > getRate(a) ? b : a));
  const worst = rated.reduce((a, b) => (getRate(b) < getRate(a) ? b : a));
  return getRate(best) === getRate(worst) ? { best: null, worst: null } : { best, worst };
}

export function insightsFor(summary) {
  const { best: bestDay, worst: worstDay } = extremes(summary.days, (d) => d.rate);
  const { best: bestHabit, worst: worstHabit } = extremes(summary.habitStats, (s) => s.rate);
  const topReason = summary.reasons.find((r) => r.id !== 'unspecified') || null;
  return { bestDay, worstDay, bestHabit, worstHabit, topReason };
}

export function rateDelta(summary, prev) {
  if (summary.rate === null || !prev || prev.rate === null) return null;
  return Math.round((summary.rate - prev.rate) * 100);
}

export function describeWeek(summary, prev) {
  if (summary.rate === null) return ['No finished days in this week yet.'];

  const { bestDay, worstDay, bestHabit, worstHabit, topReason } = insightsFor(summary);
  const delta = rateDelta(summary, prev);
  const lines = [`Completed ${summary.done} of ${summary.eligible} check-ins (${percent(summary.rate)}).`];

  if (delta !== null) {
    lines.push(delta === 0 ? 'Same as the week before.' : `${delta > 0 ? 'Up' : 'Down'} ${Math.abs(delta)} pts from the week before.`);
  }
  if (bestDay) {
    lines.push(`Strongest day: ${weekday(bestDay)} (${percent(bestDay.rate)}). Toughest day: ${weekday(worstDay)} (${percent(worstDay.rate)}).`);
  }
  if (bestHabit) {
    lines.push(`Most consistent: ${bestHabit.habit.name} (${percent(bestHabit.rate)}). Most missed: ${worstHabit.habit.name} (${percent(worstHabit.rate)}).`);
  }
  if (topReason) {
    lines.push(`Most common reason for misses: ${topReason.label.toLowerCase()} (${topReason.count}).`);
  }
  return lines;
}

// Template-based starting point for the coach. Always edited and sent by the coach.
export function draftFeedback({ name, summary, prev }) {
  const firstName = name.trim().split(' ')[0];
  const parts = [`Hi ${firstName},`];

  if (summary.rate === null) {
    parts.push("There isn't much data for this week yet. Let's start with one small habit you can do in two minutes.");
    return parts.join('\n\n');
  }

  const { bestHabit, worstHabit, topReason } = insightsFor(summary);
  parts.push(
    bestHabit
      ? `Nice work on ${bestHabit.habit.name} this week (${percent(bestHabit.rate)}).`
      : `You completed ${percent(summary.rate)} of your check-ins this week.`
  );

  const delta = rateDelta(summary, prev);
  if (delta !== null && delta !== 0) {
    parts.push(`That's ${delta > 0 ? 'up' : 'down'} ${Math.abs(delta)} points from the week before.`);
  }
  if (topReason) {
    parts.push(`The most common reason things slipped was "${topReason.label.toLowerCase()}".`);
  }

  const target = worstHabit?.habit.name || 'your hardest habit';
  const suggestions = {
    time: `try a two-minute version of ${target}.`,
    forgot: `attach ${target} to something you already do every day, like your first coffee.`,
    priority: `schedule ${target} before your first meeting so it doesn't compete with work.`,
    energy: `move ${target} earlier in the day.`,
  };
  parts.push(`For next week, ${suggestions[topReason?.id] || 'pick one habit to protect and keep the rest flexible.'}`);
  parts.push('How does that sound?');
  return parts.join('\n\n');
}

export function median(values) {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

export function formatDuration(ms) {
  const seconds = Math.round(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  return `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, '0')}s`;
}
